template: 'qwe'
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
branches: [master]
categories:
  - title: 🔨 Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🚀 New Features
    label: Feature
exclude-labels:
  - 'dependencies'
change-template: '- #$NUMBER: $TITLE by @$AUTHOR'
template: |
  # Changes
  $CHANGES
