name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: test
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo $GITHUB_CONTEXT
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        $env:RUST_BACKTRACE=1
        cd Vindicta-Addon
        .\tools\buildv2.ps1
        
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: Vindicta-Addon/release

    - uses: actions/upload-artifact@v1
      with:
        name: dev
        path: Vindicta-Addon/dev

  update-release-draft:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
    - name: Download dev
      uses: actions/download-artifact@v1
      with:
        name: dev
    - name: Upload ftp
      uses: sebastianpopp/git-ftp-action@2.1.0
      with:
        url: ftp://${{ secrets.FTP_SERVER }}/ugs-eu-germany-1.armahosts.com_2322/mpmissions
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        syncroot: "dev"
        #remoteDir: "/ugs-eu-germany-1.armahosts.com_2322/mpmissions"
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Zip for Release
      run: |
        cd build
        zip -r vindicta.zip @vindicta
        ls
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/vindicta.zip
        asset_name: vindicta.zip
        asset_content_type: application/zip

        
